version: '3'

services:

  app:
    stdin_open: true
    build: ./app
    ports:
      - 3000:3000
    volumes:
      - "./app/node_modules:/app/node_modules"
      - "./app:/app"

  api:
    depends_on:
      - db
    stdin_open: true
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - 3001:3001
    volumes:
      - "./api:/api"

  db:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api_development
    ports:
      - "5452:5432"